# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sweet2-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sweet2-miuicamera

PRODUCT_PACKAGES += \
    MiuiCamera \
    libMiStereoFactoryCalibAnalyzeBin_qual \
    libmiStereoCalibLib_qual \
    libgui-xiaomi \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0
